-- LvL base Supabase/PostgreSQL schema.
-- Run this first in a fresh Supabase project, before community_schema.sql and migrations/.
-- This file creates the core tables that app.py already expects to exist.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  first_name varchar(60) not null default '',
  last_name varchar(60) not null default '',
  nickname varchar(24) not null,
  username varchar(24) not null,
  display_name varchar(120) not null default '',
  email varchar(255) not null,
  password_hash text not null,
  gender varchar(40),
  birthday date,
  profile_photo_url text,
  theme_color char(7) not null default '#1D9BF0',
  avatar_color char(7) not null default '#1D9BF0',
  bio varchar(180) not null default '',
  location varchar(80) not null default '',
  website varchar(255) not null default '',
  is_verified boolean not null default false,
  verification_token text,
  total_xp integer not null default 0 check (total_xp >= 0),
  level integer not null default 1 check (level >= 1),
  xp_today integer not null default 0 check (xp_today >= 0),
  last_xp_reward_date date,
  badge_color char(7) not null default '#71767B',
  activity_title varchar(40) not null default 'New Adventurer',
  profile_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_username_key unique (username),
  constraint users_nickname_key unique (nickname),
  constraint users_email_key unique (email),
  constraint users_username_format check (username ~ '^[a-z0-9_]{3,24}$'),
  constraint users_nickname_format check (nickname ~ '^[a-z0-9_]{3,24}$')
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  content varchar(280) not null default '',
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint posts_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  user_id bigint not null,
  comment varchar(280) not null,
  created_at timestamptz not null default now(),
  constraint comments_post_id_fkey foreign key (post_id) references public.posts(id) on delete cascade,
  constraint comments_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade
);

create table if not exists public.follows (
  id bigint generated by default as identity unique,
  follower_id bigint not null,
  following_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint follows_follower_id_fkey foreign key (follower_id) references public.users(id) on delete cascade,
  constraint follows_following_id_fkey foreign key (following_id) references public.users(id) on delete cascade,
  constraint follows_no_self check (follower_id <> following_id)
);

create table if not exists public.likes (
  id bigint generated by default as identity unique,
  user_id bigint not null,
  post_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id),
  constraint likes_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade,
  constraint likes_post_id_fkey foreign key (post_id) references public.posts(id) on delete cascade
);

create table if not exists public.reposts (
  user_id bigint not null,
  post_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id),
  constraint reposts_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade,
  constraint reposts_post_id_fkey foreign key (post_id) references public.posts(id) on delete cascade
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null,
  receiver_id bigint not null,
  content varchar(1000) not null default '',
  is_read boolean not null default false,
  attachment_url text,
  attachment_type text,
  attachment_name text,
  deleted_for_everyone boolean not null default false,
  deleted_by_sender boolean not null default false,
  deleted_by_receiver boolean not null default false,
  created_at timestamptz not null default now(),
  constraint messages_sender_id_fkey foreign key (sender_id) references public.users(id) on delete cascade,
  constraint messages_receiver_id_fkey foreign key (receiver_id) references public.users(id) on delete cascade,
  constraint messages_no_self check (sender_id <> receiver_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  actor_id bigint not null,
  type varchar(40) not null,
  post_id bigint,
  message_id bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint notifications_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade,
  constraint actor_id foreign key (actor_id) references public.users(id) on delete cascade,
  constraint notifications_post_id_fkey foreign key (post_id) references public.posts(id) on delete set null,
  constraint notifications_message_id_fkey foreign key (message_id) references public.messages(id) on delete set null
);

create table if not exists public.friendships (
  id bigint generated by default as identity unique,
  user_1 bigint not null,
  user_2 bigint not null,
  action_user_id bigint not null,
  status varchar(20) not null default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_1, user_2),
  constraint friendships_user_1_fkey foreign key (user_1) references public.users(id) on delete cascade,
  constraint friendships_user_2_fkey foreign key (user_2) references public.users(id) on delete cascade,
  constraint friendships_action_user_id_fkey foreign key (action_user_id) references public.users(id) on delete cascade,
  constraint friendships_ordered check (user_1 < user_2),
  constraint friendships_no_self check (user_1 <> user_2)
);

create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  event_type varchar(40) not null,
  event_key varchar(120) not null,
  points integer not null check (points >= 0),
  reward_date date not null default current_date,
  created_at timestamptz not null default now(),
  constraint xp_events_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade,
  constraint xp_events_once unique (user_id, event_type, event_key)
);

create index if not exists idx_users_created_at on public.users(created_at desc);
create index if not exists idx_users_level on public.users(level desc, total_xp desc);
create index if not exists idx_posts_user_created on public.posts(user_id, created_at desc);
create index if not exists idx_posts_created on public.posts(created_at desc);
create index if not exists idx_comments_post_created on public.comments(post_id, created_at);
create index if not exists idx_comments_user_created on public.comments(user_id, created_at desc);
create index if not exists idx_follows_following on public.follows(following_id, created_at desc);
create index if not exists idx_likes_post on public.likes(post_id, created_at desc);
create index if not exists idx_reposts_post on public.reposts(post_id, created_at desc);
create index if not exists idx_messages_receiver_read on public.messages(receiver_id, is_read, created_at desc);
create index if not exists idx_messages_sender_receiver on public.messages(sender_id, receiver_id, created_at desc);
create index if not exists idx_notifications_user_read on public.notifications(user_id, is_read, created_at desc);
create index if not exists idx_notifications_actor on public.notifications(actor_id, created_at desc);
create index if not exists idx_xp_events_daily on public.xp_events(user_id, event_type, reward_date);

alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;
alter table public.likes enable row level security;
alter table public.reposts enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.friendships enable row level security;
alter table public.xp_events enable row level security;
