-- Add backend-owned saved post drafts for future compose autosave UI.
-- The Flask backend uses the Supabase service key; RLS is enabled so the
-- exposed public table is not open to browser clients by default.

create table if not exists public.post_drafts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  content varchar(280) not null default '',
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint post_drafts_not_empty check (
    btrim(content) <> ''
    or nullif(btrim(coalesce(image_url, '')), '') is not null
  )
);

create index if not exists idx_post_drafts_user_updated
  on public.post_drafts(user_id, updated_at desc);

alter table public.post_drafts enable row level security;
